language: go

go:
  - 1.8

install:
  - go get -u github.com/golang/lint/golint
  - ./install.sh

script:
  - test -z "$(golint ./main.go | tee /dev/stderr)"
  - test -z "$(gofmt -e -l ./main.go | tee /dev/stderr)"

deploy:
  provider: script
  script: ./bin/up
  after_success: ./bin/up url

env:
  global:
    AWS_REGION: us-west-2
