language: go

go:
  - 1.8

before_install:
  - go get -u github.com/golang/lint/golint
  - curl -sfLO https://raw.githubusercontent.com/apex/up/master/install.sh

install:
  - sh install.sh -b ./bin
  - ./bin/up version

script:
  - test -z "$(golint ./main.go | tee /dev/stderr)"
  - test -z "$(gofmt -e -l ./main.go | tee /dev/stderr)"

deploy:
  provider: script
  script: ./bin/up
  skip_cleanup: true

after_success:
  - ./bin/up url

env:
  global:
    AWS_REGION: us-west-2
