language: go

go:
  - 1.8

install:
  - go get -u github.com/golang/lint/golint
  - wget https://raw.githubusercontent.com/apex/up/master/install.sh
  - sudo ./install.sh

script:
  - test -z "$(golint ./main.go | tee /dev/stderr)"
  - test -z "$(gofmt -e -l ./main | tee /dev/stderr)"

deploy:
  provider: script
  script: up

env:
  global:
    AWS_REGION: us-west-2
